version: '3'
services:
  node:
    container_name: node
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./:/app
    command: sh -c "npm start"
    ports:
    - "3000:3000"
